CREATE TABLE model_info (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    model_name VARCHAR(1023) NOT NULL,
    model_task VARCHAR(255) NOT NULL,
    run_id VARCHAR(255) NOT NULL,
    path VARCHAR(1023) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL
);

CREATE TABLE optimizer_info (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    optimizer_name VARCHAR(255) NOT NULL,
    accelerator VARCHAR(255) NOT NULL,
    argument JSON NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL
);

CREATE TABLE model_optimizer (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    model_id BIGINT NOT NULL,
    optimizer_id BIGINT NOT NULL,
    FOREIGN KEY (model_id) REFERENCES model_info(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (optimizer_id) REFERENCES optimizer_info(id) ON DELETE CASCADE ON UPDATE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL
);

CREATE TABLE model_tasks (
    pk UUID NOT NULL DEFAULT UUID() PRIMARY KEY,
    task_uuid UUID NOT NULL,
    progress_status BOOLEAN NOT NULL DEFAULT FALSE,
    model_name VARCHAR(511) NOT NULL,
    task_type VARCHAR(255) NOT NULL,
    model_path_output VARCHAR(1023) DEFAULT NULL,
    kubeflow_experiment_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL
); 